New article: Catching dreams
perladvent/Perl-Advent pull request #169
Opened 2022-08-05 10:43 UTC by thibaultduponchelle

Hello,

Here is my second article for Perl advent calendar 🎅🏼 

I probably need some help to arrange a bit the story in addition to usual edits!

2022-08-06 05:12 UTC, s1037989 commented
I haven't started reading your article yet, but I think it would be easiest -- like last time -- for the article to be merged and for me to make a PR on it rather than to review yours with comments throughout.  So I'll reviews and approve yours first.

2022-08-06 05:13 UTC, s1037989 approved these changes
I'll review via PR as opposed to via comments.

2022-08-06 05:15 UTC, s1037989 commented
I guess my approval isn't good enough.  :)

2022-08-06 05:39 UTC, s1037989 commented
Dang it...  I'll never get used to the fact that I need to go to the forked repo...  PR submitted.

2022-08-06 06:02 UTC, thibaultduponchelle commented
Merged! Thank you a lot for the review!

2022-08-11 09:54 UTC, thibaultduponchelle commented
@adamcrussell Would you be available to review this other article? Please 🙏🏼

2022-08-11 18:09 UTC, oalders requested changes
I love it! Just a few suggestions. 🧝🏻 🥭

2022-08-11 18:09 UTC, oalders commented on 2022/incoming/catching-dreams.pod
> +	use feature state;
```suggestion
	use feature qw( state );
```

Looks like this is copy/paste from a broken SYNOPSIS: https://github.com/oliwer/mango/commit/260788cb5e3ac1c0f22f449eda61d1b941ec577f

2022-08-11 18:09 UTC, oalders commented on 2022/incoming/catching-dreams.pod
> +When it comes time to doing deliveries, Santa is interested in having records from the same area to optimize the logistics of his delivery schedule.
```suggestion
When it comes time for making deliveries, Santa is interested in having records from the same area to optimize the logistics of his delivery schedule. 
```

2022-08-11 18:09 UTC, oalders commented on 2022/incoming/catching-dreams.pod
> +	my $docs = mango->db('christmas2022')->collection('gifts')->find({where => "Atlanta"});
```suggestion
	my $docs = mango->db('christmas2022')->collection('gifts')->find({where => 'Atlanta'});
```

I think it's helpful to have the quotes be consistent.

2022-08-11 18:09 UTC, oalders commented on 2022/incoming/catching-dreams.pod
> +With the elves copious year-round notetaking of childrens' dreams, Santa can count on the elves to not miss any of the childrens' wishes for Christmas.
```suggestion
With the elves' copious year-round notetaking of children's dreams, Santa can count on the elves not to miss any of the children's wishes for Christmas. 
```

2022-08-11 18:09 UTC, oalders commented on 2022/incoming/catching-dreams.pod
> +	use Mango;
```suggestion
	use Mango ();
```

2022-08-13 12:38 UTC, thibaultduponchelle commented on 2022/incoming/catching-dreams.pod
> +Santa complained MongoDB was not Perl friendly (e.g. struggles with drivers...) which had in its history taken a controversial license... But the elves are not disciplined and decided to go with it a
Re-licensing in 2018 to SSPL. It can be considered as controversial.

2022-08-13 12:39 UTC, thibaultduponchelle commented
@oalders It's ready to merge now (or some new edits 😄)

2022-08-13 15:50 UTC, oalders approved these changes

2022-08-13 15:51 UTC, oalders commented
@thibaultduponchelle can you squash it down to one commit?

2022-08-13 15:58 UTC, thibaultduponchelle commented
> @thibaultduponchelle can you squash it down to one commit?

Ok 👍will do it

@s1037989 Can you please approve?

2022-08-13 16:08 UTC, thibaultduponchelle commented
Done! 💯

2022-08-13 16:38 UTC, merged