New article: TWVycnkgQ2hyaXN0bWFzIDop
perladvent/Perl-Advent pull request #172
Opened 2022-08-08 09:43 UTC by thibaultduponchelle

Hello,

Here is another little story about elves, Perl and MIME:base64 🎅🏼

2022-08-08 09:49 UTC, thibaultduponchelle commented
@vanHoesel Would you be available to review this article? Please 🙏🏼

2022-08-08 18:03 UTC, thibaultduponchelle commented
Hi @adamcrussell

As discussed, if you could help editing and correcting this article, it would be a great 👍🏼

2022-08-08 19:47 UTC, adamcrussell approved these changes
I like this! I especially like the style and backstory. I believe the Advent Calendar entries should have a distinct holiday theme like this. 

1. The spelling sirup is much less common than syrup. No need to change it, in my opinion.
2. I would add maybe a little more content. Another example or two. This could be fine as is, but if so inspired I think the typical Advent Calendar entry is a little longer.

2022-08-08 20:18 UTC, oalders requested changes
Love it! Just a few minor things. 🧝🏻

2022-08-08 20:18 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +On 18th of December, to celebrate the Perl birthday, elves organized a big party with cakes, waffles, pancakes and maple sirup.
> 
```suggestion
On the 18th of December, to celebrate Perl's birthday, the elves organized a big party with cakes, waffles, pancakes and maple sirup.
```

2022-08-08 20:18 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +They party like crazy but only until exactly midnight where everyone went to bed.
```suggestion
They partied like crazy but only until exactly midnight when everyone went to bed.
```

2022-08-08 20:18 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +The day after, elves walked to North Pole warehouse. To open the door and disable the alarm, as every day, they called the dedicated elf "spof" to enter the code.
```suggestion
The day after, the elves walked to North Pole warehouse. To open the door and disable the alarm, as every day, they called the dedicated elf "spof" to enter the code.
```

2022-08-08 20:18 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +He proceed and got once again "ERROR"
```suggestion
He proceeded and, once again, got "ERROR".
```

2022-08-08 20:18 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +	use MIME::Base64;
```suggestion
	use MIME::Base64 qw( decode_base64 );
```

2022-08-08 20:18 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +	use MIME::Base64;
```suggestion
	use MIME::Base64 qw( encode_base64 );
```

2022-08-08 20:18 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +You should never feed a L<Gremlin|https://en.wikipedia.org/wiki/Gremlins> after midnight but you also need to monitor closely the maple sirup consumption of elves!
```suggestion
You should never feed L<Gremlin|https://en.wikipedia.org/wiki/Gremlins> after midnight but you also need to monitor closely the maple sirup consumption of elves!
```

2022-08-09 11:49 UTC, thibaultduponchelle commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +One of the elves has little experience with IT and he immediately thought he would test L<MIME::Base64> to translate this gibberish:
Yes, good catch thx

2022-08-10 13:02 UTC, thibaultduponchelle commented
I added a paragraph upon remark of @adamcrussell and fixed all requested changes. 

Except edits in the new paragraph, I think it could be ready to merge.

2022-08-10 13:26 UTC, thibaultduponchelle commented
```
$ perl t/article_pod.t 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod 
# Subtest: 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
    # Subtest: header for 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
        ok 1 - Required field <title> is there
        ok 2 - Required field <topic> is there
        ok 3 - Required field <author> is there
        1..3
    ok 1 - header for 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
    # Subtest: pod for 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
        ok 1 - Pod checks passes
        1..1
    ok 2 - pod for 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
    1..2
ok 1 - 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
1..1
```

2022-08-11 17:52 UTC, oalders requested changes
Great stuff! Just minor suggestions.

2022-08-11 17:52 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +The above script is using environment variable to pass the secret.
```suggestion
The above script is using an environment variable to pass the secret.
```

2022-08-11 17:52 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +Aside mapple syrup, Spof enjoys doing some Perl scripting for himself the evening, so after this event he did (or at least he I<tried>).
```suggestion
Aside from maple syrup, Spof enjoys doing some Perl scripting for himself the evening, so after this event he did (or at least he I<tried>).
```

2022-08-11 17:52 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +Confused but lazy, he dig the L<MetaCPAN|https://metacpan.org/> for a solution and went with L<Acme::Base64>:
```suggestion
Confused but lazy, searched the L<MetaCPAN|https://metacpan.org/> for a solution and went with L<Acme::Base64>:
```

2022-08-11 17:52 UTC, oalders commented on 2022/incoming/TWVycnkgQ2hyaXN0bWFzIDop.pod
> +This way, C<perl> interpreter could understand the B<base64> dialect spoken by Spof! Magic!
```suggestion
This way, the C<perl> interpreter could understand the B<base64> dialect spoken by Spof! Magic!
```

2022-08-13 12:49 UTC, thibaultduponchelle commented
@oalders I updated, ready to merge?

2022-08-13 15:58 UTC, oalders commented
@thibaultduponchelle, sure. Could you squash it down to a single commit?

2022-08-13 16:04 UTC, thibaultduponchelle commented
Done

2022-08-13 16:22 UTC, oalders approved these changes
\o/

2022-08-13 16:22 UTC, oalders commented
I guess we can also squash via the merge button. I had forgotten about that.

2022-08-13 16:37 UTC, merged