SCreate professional slideshows with Mojolicious::Plugin::RevealJSubmit article
perladvent/Perl-Advent pull request #219
Opened 2022-11-24 19:52 UTC by DragosTrif

2022-11-24 20:39 UTC, oalders requested changes
Thanks for this! The format of articles is Pod, rather than markdown. You can run `perl script/new_article` in this repo to help you start your article Pod.

Pod is mentioned at https://cfp.perladvent.org/ in "Guidelines on the Articles". I'm wondering if you missed that part?

2022-11-24 21:26 UTC, oalders commented
See also https://staging.perladvent.org/FAQ-submit.html

2022-11-24 22:45 UTC, DragosTrif commented
I have update to pod. But code section like this one are not showing up.
Could you please help?


=begin perl

use strict;
use warnings;

use lib 'lib';

use Foo;
use feature 'say';

# reveal begin object_creation
my $o = Foo->new();
# reveal end object_creation

$o->print_foo_bar();
$o->test(1);
say $o->test();

say $o->test();

=end perl

În joi, 24 nov. 2022 la 23:27, Olaf Alders ***@***.***> a
scris:

> See also https://staging.perladvent.org/FAQ-submit.html
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/perladvent/Perl-Advent/pull/219#issuecomment-1326845554>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACTJYSGWW2T3FC4VUHBD2GDWJ7MS3ANCNFSM6AAAAAASKWIISU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-25 16:56 UTC, oalders commented
> I have update to pod. But code section like this one are not showing up.
Could you please help?

Did you get this sorted?

2022-11-25 16:58 UTC, DragosTrif commented
Hi @oalders no. I'm a bit frustrated by this.

2022-11-25 17:06 UTC, oalders commented
There's a script here you can use to build the entire site: https://github.com/perladvent/Perl-Advent/blob/main/script/build-site.sh

You can the deploy the site locally.

```bash
cd out
plackup -MPlack::App::Directory -e 'Plack::App::Directory->new(root=>".");' -p 8080
```

If you do it this way, are you still seeing the issue? If so, please share a screen shot.

2022-11-25 17:32 UTC, thibaultduponchelle commented
Current preview:
![perlrevealjs](https://user-images.githubusercontent.com/580360/204033638-58f0fc2d-8541-4b9a-b65e-c0541cec6d3d.png)

Please edit links `L<Your Text|http://example.com>`
POD error at the end

2022-11-25 18:11 UTC, DragosTrif commented
I have fixed the links.

2022-11-25 18:47 UTC, DragosTrif commented
Fix it with verbatim paragraph

2022-11-25 18:57 UTC, oalders requested changes
Thanks so much. Made a few suggestions.

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +Topic: Create professional slideshows with Mojolicious::Plugin::RevealJS
```suggestion
Title: Create Professional Slideshows with Mojolicious::Plugin::RevealJS
Topic: Create Professional Slideshows with Mojolicious::Plugin::RevealJS
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +=head1 Create professional slideshows with Mojolicious::Plugin::RevealJS
```suggestion
=head1 Create Professional Slideshows with Mojolicious::Plugin::RevealJS
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +Santa's elf had a problem. He had to write very fast a presentation and show it to a bunch of new elf's.
```suggestion
Santa's elf had a problem. He had to write a presentation very fast and show it to a bunch of new elves. 
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +The elf started to look on Metacpan and found this module: L<Mojolicious::Plugin::RevealJS|https://metacpan.org/pod/Mojolicious::Plugin::RevealJS>
```suggestion
The elf started to look on MetaCPAN and found this module: L<Mojolicious::Plugin::RevealJS|https://metacpan.org/pod/Mojolicious::Plugin::RevealJS>
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +Now he could generate an mojo lite app using:
```suggestion
Now he could generate a Mojo lite app using:
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +    <h4> Create professional slideshows with Mojolicious::Plugin::RevealJS</h4>
```suggestion
    <h4> Create Professional Slideshows with Mojolicious::Plugin::RevealJS</h4>
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +so instead of html tags he used  Markdown format:
```suggestion
so instead of HTML tags, he used  Markdown format:
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +    #### Create professional slideshows with Mojolicious::Plugin::RevealJS
```suggestion
    #### Create Professional Slideshows with Mojolicious::Plugin::RevealJS
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +which pointed the file and the correct syntax highlight:
```suggestion
which points to the file to include and the correct syntax highlighting to use:
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +He opened the file and added some magic comments  in it:
```suggestion
Disaster! The C<examples/test.pl> file has too much code in it. The new elves will be lost for ever if they see this. 
He opened the file and added some magic comments to it:
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +    <h4> Create professional slideshows with Mojolicious::Plugin::RevealJS</h4>
```suggestion
    <h4> Create Professional Slideshows with Mojolicious::Plugin::RevealJS</h4>
```

2022-11-25 18:57 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +which also allowed him to control his presentation.
```suggestion
Now when he pressed C<s>, he could see 
the notes from each slide in a new window,
which also allowed him to control his presentation.
```

2022-11-26 05:38 UTC, DragosTrif commented
accepted the suggestions

2022-11-27 15:02 UTC, thibaultduponchelle commented
Nice article @DragosTrif  I did some suggestions. Not tested the code.

2022-11-27 15:03 UTC, thibaultduponchelle requested changes

2022-11-27 19:30 UTC, DragosTrif commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +    app->start;
That did not work for me. I used to test perldoc and pod2html.  I asked on stack overflow and got this solution:  https://stackoverflow.com/questions/74575867/perldoc-does-not-display-text-between-section.

2022-11-27 19:54 UTC, thibaultduponchelle commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +    app->start;
Not working with standard POD formatting but with advent calendar POD

2022-11-29 09:47 UTC, thibaultduponchelle requested changes

2022-11-29 10:39 UTC, DragosTrif commented
# Subtest: 2022/articles/mojolicious_plugin_revealjS.pod
    # Subtest: header for 2022/articles/mojolicious_plugin_revealjS.pod
        ok 1 - Required field <title> is there
        ok 2 - Required field <topic> is there
        ok 3 - Required field <author> is there
        1..3
    ok 1 - header for 2022/articles/mojolicious_plugin_revealjS.pod
    # Subtest: pod for 2022/articles/mojolicious_plugin_revealjS.pod
        ok 1 - Pod checks passes
        1..1
    ok 2 - pod for 2022/articles/mojolicious_plugin_revealjS.pod
    1..2
ok 1 - 2022/articles/mojolicious_plugin_revealjS.pod

2022-11-29 10:43 UTC, thibaultduponchelle approved these changes

2022-11-29 10:44 UTC, thibaultduponchelle commented
Thank you @DragosTrif I just approved it :+1:

2022-11-29 11:13 UTC, DragosTrif commented
![Screenshot from 2022-11-29 13-11-21](https://user-images.githubusercontent.com/10918984/204514793-81add096-cd3a-4845-bf77-ad1c2dc8fada.png)
victory

2022-11-29 21:06 UTC, oalders requested changes
Thanks for working with us on this. We are very close to wrapping this one up.

2022-11-29 21:06 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +
```suggestion
```

The title will be created from the `Title` in the metadata above.

2022-11-29 21:06 UTC, oalders commented on 2022/articles/mojolicious_plugin_revealjS.pod
> +so instead of HTML tags, he used  Markdown format:
```suggestion
Time was ticking. The elf need to speed things up. 
So, instead of HTML tags, he used Markdown format:
```

2022-11-29 21:12 UTC, oalders approved these changes

2022-11-29 21:13 UTC, merged