New article: What did Santa forget?
perladvent/Perl-Advent pull request #227
Opened 2022-11-27 15:53 UTC by bbrtj

#226 

Not sure what to do with blocks presenting output, so I left them idented.

2022-11-27 16:00 UTC, thibaultduponchelle commented
Preview:
![forget](https://user-images.githubusercontent.com/580360/204144781-72480bfe-d7fa-4f27-946e-dbff8d43c414.png)

2022-11-27 16:01 UTC, thibaultduponchelle commented
I would have added a line in the conclusion like: "Thanks to this, if you were nice, dear reader, you do not have any chance to be forgotten" (but better said)

2022-11-27 16:02 UTC, thibaultduponchelle commented
The article is OK for me

2022-11-27 16:02 UTC, thibaultduponchelle approved these changes

2022-11-27 16:21 UTC, bbrtj commented
Well I don't know, I don't really like obvious conclusions. But if you think the article ends weirdly or unexpectedly I'll try to come up with something.

2022-11-27 16:23 UTC, thibaultduponchelle commented
> Well I don't know, I don't really like full-blown / obvious conclusions. But if you think the article ends weirdly or unexpectedly I'll try to come up with something.

No it's OK, was just a proposal, let's keep like this then

2022-11-28 10:36 UTC, openstrike requested changes
This looks in good shape. Just a few minor suggestions to make it read more naturally.

2022-11-28 10:36 UTC, openstrike commented on 2022/incoming/what-did-santa-forget-.pod
> +Would be silly not to deliver a present to someone who has been trying the
Suggestion: s/Would/It would/

2022-11-28 10:36 UTC, openstrike commented on 2022/incoming/what-did-santa-forget-.pod
> +whole year to be nice. Luckily, to avoid such blunder, he made a list
Suggestion: s/such blunder/such a blunder/

2022-11-28 10:36 UTC, openstrike commented on 2022/incoming/what-did-santa-forget-.pod
> +elves how should he do it, and they suggested giving a try to recently released
Maybe "asked the elves"?

2022-11-28 11:06 UTC, bbrtj commented on 2022/incoming/what-did-santa-forget-.pod
> +Would be silly not to deliver a present to someone who has been trying the
++

2022-11-28 11:06 UTC, bbrtj commented on 2022/incoming/what-did-santa-forget-.pod
> +whole year to be nice. Luckily, to avoid such blunder, he made a list
++

2022-11-28 11:07 UTC, bbrtj commented on 2022/incoming/what-did-santa-forget-.pod
> +elves how should he do it, and they suggested giving a try to recently released
++

2022-11-28 11:07 UTC, bbrtj commented
Thanks @openstrike, fixed.

2022-11-28 11:42 UTC, openstrike approved these changes
Thanks, all looks good now.

2022-11-28 11:49 UTC, thibaultduponchelle commented
Thank you @openstrike 
Thank you @bbrtj 

I merge it now

2022-11-28 11:49 UTC, merged