(WIP) First draft of CPAN::Audit article
perladvent/Perl-Advent pull request #233
Opened 2022-11-29 04:31 UTC by briandfoy

This is as far as I got tonight, but that's about  how it will look.

2022-11-29 07:53 UTC, thibaultduponchelle commented
Preview:
![audit](https://user-images.githubusercontent.com/580360/204470574-b6e9d375-1462-430a-8e06-44ccfa8c9535.png)

2022-11-29 07:54 UTC, thibaultduponchelle commented
The Christmas 🎅🏼 story is missing, but you know this 😄

2022-11-29 08:21 UTC, thibaultduponchelle commented
I like CPAN::Audit :heart: 

Verified the links
Verified the code snippets

2022-11-29 10:22 UTC, thibaultduponchelle requested changes

2022-11-29 15:38 UTC, briandfoy commented
> The Christmas 🎅🏼 story is missing, but I think you know this 😄

I've never made a Christmas story in an advent article. Is that something that has to be there?

2022-11-29 15:46 UTC, oalders commented
> I've never made a Christmas story in an advent article. Is that something that has to be there?

Judging by past articles, it seems to come down to the author's preference.

2022-11-29 15:55 UTC, oodler577 commented
fyi, people might wonder which bdf this is 😄, obviously author's preference

![image](https://user-images.githubusercontent.com/69679854/204577906-bc71c2e7-aaa2-47e4-bb69-8400516605f7.png)

2022-11-29 19:08 UTC, oodler577 commented
> @oodler577 I've missed what you're trying to convey. What do you think needs to change?

Sorry for not being clear. I was wondering if the default _gravitar_ was what was wanted, that's all.

![image](https://user-images.githubusercontent.com/69679854/204623100-c6966fab-d252-4d2a-b741-9e130fa2ddaf.png)

2022-12-01 06:38 UTC, briandfoy commented on 2022/incoming/cpan-audit.pod
> +L<CPAN::Audit> digests those YAML files to create L<CPAN::Audit::DB>
There should all be fixed to just `C<>` now.

2022-12-01 06:39 UTC, briandfoy commented
The gravatar issue should be fixed.

2022-12-01 06:41 UTC, briandfoy commented
I'm pretty close to the final edits on this article, and I'll read it again tomorrow. I'm not very precious about the edits, so if someone wants to adjust and publish it, go for it. Until then I might fiddle with it a bit more.

2022-12-02 07:18 UTC, thibaultduponchelle requested changes

2022-12-02 07:18 UTC, thibaultduponchelle commented on 2022/incoming/cpan-audit.pod
> +everything in your `@INC`. Fix some of those by upgrading modules,
```suggestion
everything in your C<@INC>. Fix some of those by upgrading modules,
```

2022-12-02 07:18 UTC, thibaultduponchelle commented on 2022/incoming/cpan-audit.pod
> +=head Check a module
```suggestion
=head2 Check a module
```

2022-12-02 07:28 UTC, thibaultduponchelle commented on 2022/incoming/cpan-audit.pod
> +=head Check a module
This is what is reported by failed GitHub action

2022-12-02 12:04 UTC, thibaultduponchelle commented
I did some suggestions, overall sounds good to me :+1:

2022-12-06 03:13 UTC, oalders commented on 2022/incoming/cpan-audit.pod
> +	% cpan-audit installed
```suggestion
    % cpan CPAN::Audit
    % cpan-audit installed
```

2022-12-06 03:13 UTC, oalders commented on 2022/incoming/cpan-audit.pod
> +These reports come mostly from L<MITRE|https://www.cve.org> and it's
```suggestion
These reports come mostly from L<MITRE|https://www.cve.org> and its
```

2022-12-06 03:14 UTC, oalders commented on 2022/incoming/cpan-audit.pod
> +library of Common Vulnerabilities and Exposures, or just CVE, that's
```suggestion
library of Common Vulnerabilities and Exposures, or just CVE, that
```

2022-12-06 03:15 UTC, oalders approved these changes

2022-12-06 03:16 UTC, merged

2022-12-06 03:16 UTC, oalders commented
Thanks @briandfoy and @thibaultduponchelle!