New article: relocatable-perl.pod
perladvent/Perl-Advent pull request #246
Opened 2022-11-30 20:49 UTC by skaji

I’m sorry I’m late.
This is an article for #187

2022-11-30 20:57 UTC, oalders approved these changes
⭐ Looks great!!!

2022-12-02 07:06 UTC, thibaultduponchelle requested changes

2022-12-02 07:06 UTC, thibaultduponchelle commented on 2022/incoming/relocatable-perl.pod
> +It is true that you, an experienced perl hacker, could build perl v5.36 by yourself.
```suggestion
It is true that you, an experienced Perl hacker, could build perl v5.36 by yourself.
```

2022-12-02 07:06 UTC, thibaultduponchelle commented on 2022/incoming/relocatable-perl.pod
> +But people who are not very familiar with perl rarely build perl from source.
```suggestion
But people who are not very familiar with Perl rarely build perl from source.
```

2022-12-02 07:06 UTC, thibaultduponchelle commented on 2022/incoming/relocatable-perl.pod
> +But people who are not very familiar with perl rarely build perl from source.
I admit this one sounds strange

2022-12-02 07:07 UTC, thibaultduponchelle commented on 2022/incoming/relocatable-perl.pod
> +so that you are ready to use CPAN modules!
This is great!

2022-12-02 07:08 UTC, thibaultduponchelle approved these changes

2022-12-02 07:09 UTC, merged