Santa tackles Bitcoin, part 1
perladvent/Perl-Advent pull request #303
Opened 2023-10-26 04:52 UTC by bbrtj

I thought I'll make it a two part article since it already is quite big and I don't want the second part to feel rushed. The second one should be shorter though.

2023-10-26 13:38 UTC, oalders commented
> I thought I'll make it a two part article

👍🏻

2023-10-26 19:46 UTC, bbrtj commented
I have fixed the English to the best of my ability, but I'm sure it should still be looked at by a native speaker.

2023-11-25 16:20 UTC, oalders commented
Closes #298

2023-12-01 03:30 UTC, oalders requested changes
This is really great. Thank you for writing this article. I know very little about Bitcoin and I found this to be a very interesting introduction. I just had a few comments. 

To address your comment above, I don't think we need to force every article into a native English speaker's voice as we'll lose some of the charm along the way.

What I'd like to do once these points have been addressed is merge the PR and then make a few small tweaks which should not detract from the intended meaning of the article. Once that is done, if you object to any of the changes we can certainly address that. That seems to me to offer a more streamlined approach than going back and forth on comma placement etc.

2023-12-01 06:28 UTC, bbrtj commented on 2023/incoming/santa-tackles-bitcoin-part-one.pod
> +say "Your mnemonic is <$mnemonic>";
`say` is imported by `use v5.36;`, will a comment like the following one do?

`# (say function is a part of 5.36 version bundle)`

2023-12-01 16:40 UTC, bbrtj commented on 2023/incoming/santa-tackles-bitcoin-part-one.pod
> +# use purpose 84, which will create Segregated Witness addresses
Added a sentence of explanation with a link to wikipedia, thanks!

2023-12-01 16:44 UTC, oalders approved these changes

2023-12-01 18:27 UTC, oalders approved these changes
\o/

2023-12-01 18:28 UTC, merged

2023-12-01 22:02 UTC, oalders commented
@bbrtj the edited article is at #303. I will merge and release shortly as it's scheduled for Dec 2. Let me know if there's anything you want to change, even after publication. I think it makes sense to run part 2 on Dec 3.

2023-12-02 12:00 UTC, openstrike commented on 2023/incoming/santa-tackles-bitcoin-part-one.pod
> +hex string can be broadcasted to the Bitcoin network at any time, since the
s/broadcasted/broadcast/

2023-12-02 14:38 UTC, bbrtj commented on 2023/incoming/santa-tackles-bitcoin-part-one.pod
> +trend comes much to displease of the Kriss Kringle.
Thanks, there were some changes done by Olaf before publishing, the word displease was replaced with displeasure. If this sentence isn't wrong then I'd like to keep it as it was published :)

2023-12-02 14:39 UTC, bbrtj commented on 2023/incoming/santa-tackles-bitcoin-part-one.pod
> +hex string can be broadcasted to the Bitcoin network at any time, since the
Fixed by Olaf

2023-12-02 15:22 UTC, oalders commented
Thanks @openstrike! My bad for not letting you know about my edits. Was scrambling a bit to get that one out on time. 😅