First draft of Catalyst file upload checking and HTML scrubbing article
perladvent/Perl-Advent pull request #317
Opened 2023-11-26 14:12 UTC by bigpresh

Initial draft - would like to find time to polish further, as it's a bit short and a bit dry at present, but work, personal life, kids and now illness have been leaving me little extra time.

2023-11-27 00:30 UTC, oalders commented
Close #299

2023-12-03 02:22 UTC, oalders commented on 2023/incoming/html-xss-scrubbing-and-file-upload-validation-in-catalyst.pod
> +checking so that if a action hasn't specified that it expects file uploads,
```suggestion
checking so that if an action hasn't specified that it expects file uploads,
```

2023-12-03 02:22 UTC, oalders commented on 2023/incoming/html-xss-scrubbing-and-file-upload-validation-in-catalyst.pod
> +* Validating file uploads are expected and are the expected type
```suggestion
* Validating that file uploads are expected and are the expected type
```

2023-12-03 02:23 UTC, oalders commented on 2023/incoming/html-xss-scrubbing-and-file-upload-validation-in-catalyst.pod
> +    # (determined from file content by File::MMagic, not what the client said)
Maybe add a note on why this is important?

2023-12-03 02:25 UTC, oalders commented on 2023/incoming/html-xss-scrubbing-and-file-upload-validation-in-catalyst.pod
> +parameters using L<HTML::Scrubber>.
Neat. I didn't know about `HTML::Scrubber` when I was writing `HTML::Restrict`. 🤔

2023-12-03 02:27 UTC, oalders commented on 2023/incoming/html-xss-scrubbing-and-file-upload-validation-in-catalyst.pod
> +and released a new version.  Since then we added more - including recursive
Might be helpful to link to https://neilb.org/2013/07/24/adopt-a-module.html here.

2023-12-04 21:30 UTC, bigpresh commented
Many thanks for the suggestions!  Applied and made some further tweaks, I think it's about ready.

2023-12-04 22:52 UTC, oalders requested changes
Nice. Just one more thing.

2023-12-04 22:52 UTC, oalders commented on 2023/incoming/html-xss-scrubbing-and-file-upload-validation-in-catalyst.pod
> +For example, both a shell script and an XML file aren't are both C<text/plain>
> aren't are

2023-12-05 09:17 UTC, bigpresh commented on 2023/incoming/html-xss-scrubbing-and-file-upload-validation-in-catalyst.pod
> +For example, both a shell script and an XML file aren't are both C<text/plain>
Already fixed :)

2023-12-05 18:31 UTC, oalders approved these changes
🎉 Thank you very much, @bigpresh!

2023-12-05 18:31 UTC, merged