Santa's Helpers' Helpers
perladvent/Perl-Advent pull request #318
Opened 2023-11-26 16:10 UTC by GeekRuthie

Here's the draft of my article!

2023-11-27 00:32 UTC, oalders commented
Closes #289

2023-12-05 23:20 UTC, openstrike requested changes
Very nicely written. Just an issue with the POD as detailed here.

2023-12-05 23:20 UTC, openstrike commented on 2023/incoming/santa-s-helpers-helpers.pod
> +=item L<DBIx::Class::ResultSetNames>
These 2 =item lines need a blank line between them. Alternatively just make the two modules into one =item:

`=item L<Dancer2::Plugin::DBIx::Class> and L<DBIx::Class::ResultSetNames>`

2023-12-05 23:20 UTC, openstrike commented on 2023/incoming/santa-s-helpers-helpers.pod
> +=item L<DBIx::Class::MoreHelpers>
Same here: separate with a blank line or else combine into one =item

2023-12-09 10:41 UTC, openstrike approved these changes
Perfect.

2023-12-09 15:28 UTC, merged