Mooish Attribute Shortcuts For Everyone!
perladvent/Perl-Advent pull request #339
Opened 2023-12-03 13:52 UTC by bbrtj

I don't like the ending very much, so I'm open to suggestions.

Closes #334

2023-12-07 02:27 UTC, oalders commented
@openstrike -- any suggestions for the ending?

2023-12-07 10:43 UTC, openstrike commented
The ending's OK, if a little abrupt. I wouldn't worry about it.

The article talks about [MooseX::Extended](https://metacpan.org/pod/MooseX::Extended) but doesn't seem to mention whether or not you can use that and [Mooish::AttributeBuilder](https://metacpan.org/pod/Mooish::AttributeBuilder) together in the same module/script without issue. Given that they provide the same keywords that might confuse someone like me who rarely uses Moose. Maybe a sentence or two on that might tie it all together?

2023-12-07 10:56 UTC, bbrtj commented
@openstrike fair point, I don't think there's any gain from Mooish::AttributeBuilder if you already use MooseX::Extended, but the article may not state that clearly. I'll change it later to be more clear about the purpose of the module.

2023-12-07 20:29 UTC, bbrtj commented
@openstrike could you take a look again? Had more writing inspiration today, I think the article is much better now.

2023-12-07 22:32 UTC, openstrike requested changes
Thanks - looks really good with the re-wording. Just a couple of typos introduced with this to fix and I think the article will be ready to go!

2023-12-07 22:32 UTC, openstrike commented on 2023/incoming/mooish-attribute-shortcuts-for-everyone-.pod
> +build your attributes easier and giving them meaning. It's not by any means a
```suggestion
build your attributes more easily and give them meaning. It's not by any means a
```

2023-12-07 22:32 UTC, openstrike commented on 2023/incoming/mooish-attribute-shortcuts-for-everyone-.pod
> +shortcuts, but the core functionality alone should immensly improve the code
```suggestion
shortcuts, but the core functionality alone should immensely improve the code
```

2023-12-08 15:06 UTC, openstrike approved these changes
Looks good to merge to me. Thanks.

2023-12-08 23:09 UTC, oalders commented
Thanks @bbrtj and @openstrike!

2023-12-08 23:10 UTC, merged

2023-12-08 23:12 UTC, oalders commented
This will be published for Dec 9. https://github.com/perladvent/Perl-Advent/pull/354/files