brian's Data::Rx article
perladvent/Perl-Advent pull request #444
Opened 2024-11-14 12:03 UTC by briandfoy

Here's the first draft

2024-11-17 08:29 UTC, briandfoy commented on 2024/incoming/santas-reindeer.pod
> +=end code
I added a few hints. Let's see if they work. If they do, my PR for `new_article` can be merged (#446)

2024-11-17 16:58 UTC, oalders commented
Is this ready for final review?

2024-11-17 16:58 UTC, oalders commented
Is this ready for final review?

2024-11-18 17:18 UTC, briandfoy commented
The article is about 75% there. I'll finish it up by next Monday.

2024-11-27 21:03 UTC, oalders commented
Based on commit messages, this one is ready for review?

2024-11-28 14:15 UTC, briandfoy commented
Yes, review away. Edit freely. I'll read it again later.

2024-12-01 15:32 UTC, openstrike requested changes
Just some minor fixes for grammar and typos. The article reads well. I have not tested the code/configs.

2024-12-02 02:12 UTC, briandfoy commented
All suggestions applied. Thanks for the work!

2024-12-02 10:04 UTC, openstrike approved these changes

2024-12-04 03:24 UTC, oalders commented
Thanks @briandfoy and @openstrike!

2024-12-04 03:24 UTC, merged