initial version of the 2024 christmas article
perladvent/Perl-Advent pull request #476
Opened 2024-12-03 15:28 UTC by 2shortplanks

2024-12-07 02:06 UTC, PatrickCronin requested changes
What a treat. A heartfelt summary of what Perl and the calendar has brought the world over 25 years. The only comments I have are grammatical / spelling.

2024-12-07 02:06 UTC, PatrickCronin commented on 2024/articles/2024-12-25.pod
> +about can be silly, daft, fun, and a treat!  Why not have a story about how
Doesn't read well. Maybe something like "but the instead having something to learn about" => "but instead learning about something"?

2024-12-07 02:06 UTC, PatrickCronin commented on 2024/articles/2024-12-25.pod
> +person in the Perl community has talked about optomizing projects for fun -
optomizing => optimizing

2024-12-07 02:06 UTC, PatrickCronin commented on 2024/articles/2024-12-25.pod
> +So, as I try to do every year, and on this twenty fifth year of the Perl Advent
twenty fifth should be hyphenated

2024-12-08 18:21 UTC, oalders commented
Thank you for your contribution! I'm finding that blog articles which include images have much more compelling social media previews when the article is shared. Adding an image is by no means required and you should feel free to ignore this message entirely. However, if you'd like to add an image, it's as simple as:

* Adding the image to the `2024/share/static` folder like `2024/share/static/some-graphic.png`
* Including the image as HTML in your article

The HTML would look like:

```
=for :html
<img src="some-graphic.png">

```

The trailing blank line is important as that signals that the `HTML` section is finished.

Images can most certainly be AI generated. You should also feel free to use https://search.creativecommons.org/ in order to find CC images which can be freely shared. If you choose to go this route, please provide proper attribution when including the image, if attribution is required.

Most importantly, if you don't feel like doing this, then feel free to submit your article without an image. It's *your* article and *you* need to be happy with it.

2024-12-15 18:06 UTC, oalders commented
@2shortplanks do you know when you might be able to have a look at the review comments?

2024-12-23 07:03 UTC, 2shortplanks commented on 2024/articles/2024-12-25.pod
> +modifications to manipulate the code we write to add brand new language features
Rewrote to not suck.

2024-12-23 07:42 UTC, 2shortplanks commented
@oalders Image added as requested.

You changed the title of the pull request here to suggest this article is for the 24th.  Just to remind you, the pull request currently puts it at the 25th - if you want to change that you'll need to modify things!

2024-12-23 12:15 UTC, PatrickCronin approved these changes
Looks great! Thanks!

2024-12-23 16:16 UTC, oalders commented
Thanks @PatrickCronin for the review and @2shortplanks for taking the time to write this article. I think this is a lovely way to finish up year 25. ❤️

2024-12-23 16:17 UTC, merged