Using Valiant for Validations in Agendum: A Deep Dive into DBIx::Class Integration
perladvent/Perl-Advent pull request #485
Opened 2024-12-06 17:27 UTC by jjn1056

Article for issue https://github.com/perladvent/Perl-Advent/issues/484

2024-12-08 18:20 UTC, oalders commented
Thank you for your contribution! I'm finding that blog articles which include images have much more compelling social media previews when the article is shared. Adding an image is by no means required and you should feel free to ignore this message entirely. However, if you'd like to add an image, it's as simple as:

* Adding the image to the `2024/share/static` folder like `2024/share/static/some-graphic.png`
* Including the image as HTML in your article

The HTML would look like:

```
=for :html
<img src="some-graphic.png">

```

The trailing blank line is important as that signals that the `HTML` section is finished.

Images can most certainly be AI generated. You should also feel free to use https://search.creativecommons.org/ in order to find CC images which can be freely shared. If you choose to go this route, please provide proper attribution when including the image, if attribution is required.

Most importantly, if you don't feel like doing this, then feel free to submit your article without an image. It's *your* article and *you* need to be happy with it.

2024-12-10 16:52 UTC, jjn1056 commented
@oalders you inspired me to make a logo for Valiant, please let me know if I followed your instructions correctly :)

2024-12-10 17:27 UTC, oalders commented
This is great! Do you have any peers you'd like to have review this? If not, that's fine, but I'm finding I don't have the resources to do a really deep dive on articles right now. I'm happy to fix up formatting issues etc.

2024-12-11 17:35 UTC, jjn1056 commented
@oalders I did ask three people to look at it but didn't get a lot of feedback.   I worry a bit that I'm so close to this stuff that I'm not writing something people unfamiliar with it can understand but I get everyone is busy right now.  If you look it over and feel lost let me know.   I ran it thru two grammar checkers so hopefully you won't have a ton of work on that score.

2024-12-12 11:02 UTC, openstrike requested changes
Thanks for this article. I found it very interesting and the level (for me) was just right. I've made quite a few suggestions here but they are all very minor - typos and so forth.

In case you were unaware, the badges on the metacpan page for Valiant show failures in the Linux and Windows test/coverage. I only mention because this will be the first time a lot of readers will look at it and you'll probably want to give them the best possible first impression.

2024-12-12 11:02 UTC, openstrike commented on 2024/incoming/using-valiant-for-validations-in-agendum-a-deep-dive-into-dbix-class-integration.pod
> +is covered in the full L<Valiant> documentation. But this gives you the basic idea.
```suggestion
is covered in the full L<Valiant> documentation but this gives you the basic idea.
```

2024-12-12 22:45 UTC, jjn1056 commented on 2024/incoming/using-valiant-for-validations-in-agendum-a-deep-dive-into-dbix-class-integration.pod
> +or suggestions please feel free to reach out to me via email or on the L<Valiant> github repository.  I'm
good call, I'll update

2024-12-12 22:59 UTC, jjn1056 commented
> Thanks for this article. I found it very interesting and the level (for me) was just right. I've made quite a few suggestions here but they are all very minor - typos and so forth.
> 
> In case you were unaware, the badges on the metacpan page for Valiant show failures in the Linux and Windows test/coverage. I only mention because this will be the first time a lot of readers will look at it and you'll probably want to give them the best possible first impression.

@openstrike thanks for looking thru this.   Even after reading it 10 times there's still so many grammar errors, sorry about that:(.  

I did a new release of Valiant to remove the windows tests results (I can't seem to get at action to work right no matter what) and tweaked the actions to work properly again for Mac and Linux.  So that should look like not abandoned code on Metacpan when people see it.

Thanks for the feedback.   It would be nice to get some people excited about this, I use it on a lot of projects but it would be better to not be the only one.

2024-12-12 23:08 UTC, openstrike approved these changes

2024-12-12 23:12 UTC, oalders commented
> @oalders I'm happy for this to be merged but maybe you'd like to have a quick read-through for good measure?

I trust you. 😄 Thank you so much for your help with this @openstrike!

Thanks @jjn1056 for sharing your hard work!

2024-12-12 23:12 UTC, merged